name: docker-build

on:
  push:
    branches: main

jobs:
  multi:
    runs-on: ubuntu-latest
    env: 
      VERSION: 1.0.4
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      # Archive artifacts does not work at the moment because the upload mechanism does not work
      # - name: Archive artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist-binary
      #     path: |
      #       target/release/awattar-prices
