name: docker-build

on:
  push:
    branches: main

jobs:
  multi:
    runs-on: ubuntu-latest
    env: 
      VERSION: 1.0.5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      # Archive artifacts does not work at the moment because the upload mechanism does not work
      # - name: Archive artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist-binary
      #     path: |
      #       target/release/awattar-prices
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
#          platforms: linux/amd64, linux/arm64, linux/arm64/v8, linux/arm/v7, linux/arm/v6, linux/ppc64le
          push: true
          build-args: |
            VERSION=${{env.VERSION}}
          tags: |
            registry.hp-weidinger.local/hapewe/awattar_price_fetch:latest
            registry.hp-weidinger.local/hapewe/awattar_price_fetch:${{env.VERSION}}
