name: docker-build

on:
  push:
    branches: main

jobs:
  multi:
    runs-on: ubuntu-latest
    env: 
      VERSION: 1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust multi-platform executable
        run: cargo build --release --target aarch64-linux-musl,x86_64-linux-musl

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            VERSION=${{env.VERSION}}
          tags: |
            hapewe/surreal_db_awattar_prices:latest
            hapewe/surreal_db_awattar_prices:${{env.VERSION}}

      - name: Scan image
        uses: azure/container-scan@v0
        continue-on-error: true # this might be dangerous and should be made better in future versions.
        with:
          image-name: hapewe/surreal_db_awattar_prices:${{env.VERSION}}